# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 流浪的家
subtitle: 流浪的家
description:
keywords:
author: pt
language: zh-CN
timezone:
footer: '这是页脚文字，支持**markdown**语法。'
# 导航栏，建议以/结尾。
menu:
  - name: home
    icon: fas fa-home
    url: /
  - name: archives
    icon: fas fa-archive
    url: archives/

# 侧边栏小部件
widgets:
  - widget: toc
  - widget: tagcloud
  - widget: category
  - widget: author
    avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png
    jinrishici: 柳暗花明又一村
    social: true
  - widget: plain
    icon: fas fa-bullhorn
    title: 注意啦～
    body: '本站你若喜欢，请推荐给身边的朋友哦～'
    more:
      icon: fas fa-question-circle
      url: https://xaoxuu.com/wiki/material-x/
  - widget: list
    icon: fas fa-medal
    title: 精选项目
    more:
      icon: fas fa-arrow-right
      url: https://xaoxuu.com/projects/
    rows:
      - name: 易百教程
        desc: 易百教程
        icon: fas fa-cube
        url: https://www.yiibai.com/
      - name: AXKit
        desc: iOS开源库
        icon: fas fa-cube
        url: https://xaoxuu.com/wiki/axkit/
      - name: NoticeBoard
        desc: iOS开源库
        icon: fas fa-cube
        url: https://xaoxuu.com/wiki/noticeboard/
      - name: HeartMate
        desc: iOS应用程序
        icon: fas fa-heartbeat
        url: https://xaoxuu.com/heartmate/
      - name: Material X
        desc: Hexo博客主题
        icon: fas fa-cube
        url: https://xaoxuu.com/wiki/material-x/
  - widget: list
    icon: fas fa-link
    title: 特别链接
    rows:
      - name: 关于我 / 留言板
        icon: fas fa-comment-dots
        url: https://baidu.com/
  - widget: related_posts
    
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: /
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-material-x

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git
#   repo: https://github.com/peengtao123/pt.git
#   branch: gh-pages
#   message: messagepo

deploy:
  type: sftp
  host: 47.89.13.13
  user: root
  privateKey: C:\Users\Administrator\.ssh\id_rsa
  remotePath: /root/nginx/www